### ISSUE TITLE
[QUERY] Having issues deploying function App.  Copy never seems to finish

### ISSUE THREAD

**Issue by kazman71** [Azure/azure-libraries-for-net#1061]
I am not sure if this is a Fluent issue or a FunctionApp deployment issue in general. 

I am trying to deploy a function app from a blob storage and the first time it works.  On every other time it hangs on what seems to be a copy.  After looking into Kudu console I could see the files but only some of them pushed to the file storage where the function would use them.    The code to deploy is below.  You may want more info, and I can provide.  Also an intersting thing to note is if I set the WEBSITE_DEPLOY_FROM_PACKAGE in the function app settings, the function immediately comes up and seems to be working. 

 logger.Debug($"Beginning {tries + 1} out of {maxRetry} attempts to deploy package.");
 await app.Deploy().WithPackageUri(packageUri).WithExistingDeploymentsDeleted(true).ExecuteAsync();

**Comment by weidongxu-microsoft** [comment]
WEBSITE_DEPLOY_FROM_PACKAGE is usually the preferred approach (and maybe the only approach for Linux Function App). If this works for your use case, please use it instead of MSDeploy. Maybe even ZipDeloy is also preferable to MSDeploy.

If MSDeploy is the only option, would you elaborate a bit more on "the first time it works"? For *second time*, which part changes? A new function app created, a new URL to storage for an updated app, or same function app same URL but just called a second time?

Also it will help if you can provide a small zip/war/jar package which can reproduce the issue (if it only happen to that function app).

**Comment by kazman71** [comment]
Hi thanks for the response so quickly again! 

We re-created the app service plan, storage account and generated new SAS tokens as well as pointing the target of function app binaries to one that was different from the one the blob container tha contained the artifacts was in.  We did these all close together, so unfortunately I do not know what solved the issue.  As for your question, nothing in the deployment chagne, it was literally running it twice in a row.  It seemed like the MSDeploy/ARM deadlock from what I have read, but I can't be sure.
