### ISSUE TITLE
[BUG] ListByResourceGroupAsync() making config/web call for every resource in the resource group resulting hitting the 12K read quota limit unlike it's sync counter part which make single call

### ISSUE THREAD

**Issue by rashanke2** [Azure/azure-libraries-for-net#1113]
**Describe the bug**
We are calling the API ListByResourceGroupAsync() to fetch all the resources from the specific group. We have confirmed using Fiddler that it’s making separate config call for every request in the resource group. Where as ListByResourceGroup(), it's sync counterpart of the same API, unlike the async one, it makes singe request to pull all configurations.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
var apps = await azure.AppServices.FunctionApps.ListByResourceGroupAsync(resourceGroup).ConfigureAwait(false);

**Expected behavior**
It should make a single config call. Making multiple config call is causing hitting the throttling limit. Ideally the behavior should be same in sync/async API.

**Screenshots**
![image](https://user-images.githubusercontent.com/37538221/88217596-6b834f00-cc7c-11ea-88c4-0c5fdbf4695c.png)
![image](https://user-images.githubusercontent.com/37538221/88226299-785a6f80-cc89-11ea-8cf2-d51041654e7d.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS 2017
 - Version of the Library used
Library and API Details
-	Nugget -> Assembly Microsoft.Azure.Management.ResourceManager.Fluent **version - 1.34.0**
-	Namespace used to read resource details from resource group -> Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions
-	Namespace used for Function App operations(start/stop, etc.) -> Microsoft.Azure.Management.AppService.Fluent
-	API available in Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions namespace
o	ListByResourceGroup
o	ListByResourceGroupAsync – Currently used API, which is firing too many get requests.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ y] Bug Description Added
- [ y] Repro Steps Added
- [ y] Setup information Added

**Comment by weidongxu-microsoft** [comment]
This is likely a bug on sync method. The design is bad (to send additional per resource requests), but that is the one there. For backward-compatibility I probably not able to do much.

Possible solution is to provide a *lite* version of the "list", that only does the list, and delay the config/web call to another method for detail.

**Comment by rashanke2** [comment]
Hi @weidongxu-microsoft, 

Why do you think it's a bug on sync method instead of async one? As this is async method which is making config/web call per resource. 

Currently I have used GetByResourceGroupAsync(), which served my purpose.

I have below points regarding issue.

- The sync/async behavior should be same in term of using underlying resources.
- Ideally it's a good idea to pull the required details in single call. 
- If the API is making multiple calls. It's good idea to call it out in [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.collectionactions.isupportslistingbyresourcegroup-1?view=azure-dotnet). As we discovered this issue after hitting subscription level limit.

Thanks
Ravi

**Comment by weidongxu-microsoft** [comment]
@rashanke2 

Usually no one make a bug by adding lots of code that should not be called at all, hence my feeling is that these additional requests are intentional.

Furthermore, the `config` is needed if customer subsequently calls a Update()..Apply() flow on the IFunctionApp. If it is `null`, the Update will result in incorrect behavior (by *deleting* existing config, since it creates an empty `SiteConfig` when the `SiteConfig` var is `null`).
e.g. https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/WebAppBaseImpl.cs#L444-L452

Even without Update()..Apply() flow, some properties could be wrong anyway, without that config request. https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/WebAppBaseImpl.cs#L827-L834

Hence my proposal to have a *lite* version of the list, returning only those information that can be returned by the list (without these config requests). If customer need more, a futher GET method would get details.

**Comment by weidongxu-microsoft** [comment]
Added `IWebApps.ListWebAppBasicByResourceGroupAsync` to only return basic data of the web app as `IWebAppBasic`. If one need more info, or need to do update on it, call `IWebApp.GetById` to get a full `IWebApp`.

Ideally this should be the default `ListByResourceGroupAsync`. However due to backward-compatibility I cannot change the old method.

Next release would be 1.34.1 or 1.35.0.
