### ISSUE TITLE
[BUG] StorageAccounts.ListAsync doesn't work if Azure return 'nextLink' property

### ISSUE THREAD

**Issue by janRucka** [Azure/azure-libraries-for-net#1193]
**Describe the bug**
Every time Azure returns storage accounts with [nextLink](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/list#storageaccountlistresult) property it gets ignored and you get just first page.

**To Reproduce**
For me it is having subscription with circa 120 storage accounts then approximately every few hundred calls (storage account listing calls) one will return with 'nextLink' property. In this case I won't get all storage accounts.

***Code Snippet***
```
        public async Task<IEnumerable<IStorageAccount>> ListStorageAccountsAsync(Microsoft.Azure.Management.Fluent.IAzure azure, CancellationToken cancellationToken = default)
        {
            var accounts = await azure.StorageAccounts.ListAsync(true, cancellationToken);
            return accounts; // if REST API returns 'nextLink' property then it is not all of them
        }
```

**Expected behavior**
Be able to get all storage accounts.

**Setup:**
OS: Win10
IDE : VS2019
Version: 1.35.0

**Additional context**
'accounts' variable from code snippet has private 'NextPageLink' property which is null. I am wondering whether the reason is that the property is not properly mapped (not sure it is the right piece of code though but please have a look):
[Storage](https://github.com/Azure/azure-libraries-for-net/blob/9eb0f12e3289825c86af51fa2fa4fa887d3aed92/src/ResourceManagement/Storage/Generated/Models/Page.cs#L28)
vs
[AppService](https://github.com/Azure/azure-libraries-for-net/blob/9eb0f12e3289825c86af51fa2fa4fa887d3aed92/src/ResourceManagement/AppService/Generated/Models/Page.cs#L28)
where Storage doesn't have this `[JsonProperty("nextLink")]` annotation.

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Could you take a look?

**Comment by xccc-msft** [comment]
@janRucka Thanks for reporting this. It looks the issue is caused [here](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Storage/StorageAccountsImpl.cs#L57-L60). The method of `ListNextAsync` is missing from code generator. We will look into it and try to regenerate. Thanks.

**Comment by xccc-msft** [comment]
@janRucka Have you tried to capture the response to confirm if it is from the `nextLink`? I tried to reproduce by the scenario of parallelly LIST storage accounts multiple times and get CloudException of too many requests. And as per the definition, the `nextLink` is not supported in current version we have [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2018-11-01/storage.json#L1711-L1723).

**Comment by janRucka** [comment]
@xccc-msft How many storage accounts does your subscription contains? Asking because now I have circa 160 of them and it seems to be more common than with circa 120. Also it seems that if there are newly created storage accounts it is more likely to occur. But frankly it is pure speculation; I don't know what is happening inside Azure.

I was trying to use REST API directly

> https://management.azure.com/subscriptions/{GUID}/providers/Microsoft.Storage/storageAccounts?api-version=2018-11-01

and I was able to capture response with nextLink (and of course with some of the storage accounts missing). Hence if `nextLink` is not supported it basically means that `StorageAccounts.ListAsync` cannot be relied upon.

**Comment by xccc-msft** [comment]
@janRucka Thanks for sharing more info. I tried with 150+ storage accounts and list them within 40 parallel threads by 1000 times each. As you confirmed you could capture the nextLink in the response, here is the details regarding the issue you met:
- The root cause: The property of `nextLink` is missing in the swagger so we cannot have `ListNextAsync` in our generated code. Then it cannot deal with nextLink when it appears in the response.
- The potential fix: We may plan to upgrade storage api version which contains nextLink.
- The workaround before we fix: You may try [Microsoft.Azure.Management.Storage](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage) to list storage accounts. It has expected ListNextAsync there.

**Comment by janRucka** [comment]
@xccc-msft Interesting, so the issue is actually in Azure REST API (either backward compatibility issue or swagger documentation issue). Thanks for sharing.

I can confirm that Microsoft.Azure.Management.Storage works with `nextLink`. Unfortunately for me it has different model and we use it quite a lot in our code but it is definitely a way.
