### ISSUE TITLE
Deploy image from container registry to Kubernetes (AKS)

### ISSUE THREAD

**Issue by florinciubotariu** [Azure/azure-libraries-for-net#287]
Is it possible to create a deployment after we create the cluster using the sample from this repo?
Is there an equivalent for [this sample](https://github.com/Azure-Samples/aks-java-deploy-image-from-acr-to-kubernetes) but in .NET?

**Comment by milismsft** [comment]
@florinciubotariu When I wrote the Java sample I could not find a good implementation for a Kubernetes client in .NET. Presuming that there is one today, it should be relatively simple to convert the Java sample into CSharp since the method calls to the AKS and ACR management libraries are almost exactly the same.
