### ISSUE TITLE
Azure Service Bus: 'queueName' exceeds maximum length of '50'

### ISSUE THREAD

**Issue by cpunella** [Azure/azure-libraries-for-net#32]
Hi,

I receive this error when I try to delete a queue with more than 50 characters. Is this a real limit on Azure Service Bus? Where can I find documentation about this limit?

Here there is the validation:
File: https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ServiceBus/Generated/QueuesOperations.cs 
Line: 596

p.s.: same problem with "topicName"...

Thanks,
Carmine

**Comment by anuchandy** [comment]
@cpunella this is the limit specified the in the service bus API [spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/servicebus/resource-manager/Microsoft.ServiceBus/2015-08-01/servicebus.json#L2640)

**Comment by cpunella** [comment]
Hi @anuchandy , yes, but why? 
Azure service bus doesn't have this limit, I can create queues with more that 50 characters...

**Comment by philcarbone** [comment]
This is a problem. We have queues and topics that exceed this and we need to write scripts to remove them (if we are going to shorten them) because we have way too many of them to do this behind. The Azure UI isn't friendly with bulk operations. This is a right hand talking to the left scenario. The API for c# and the API for Powershell & CLI should all have the same validation/restrictions. This is a red-face bug (in my opinion). There should be a specification that every interface is abiding by. Is this ever going to get fixed? It seems like this issue was opened and completely disregarded. :)

**Comment by hovsepm** [comment]
This was fixed in new spec https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicebus/resource-manager#tag-package-2017-04. Topic and Queue mac lengh cap of 50 was removed. I'll make sure we will update Service Bus client in v1.7.

**Comment by philcarbone** [comment]
Awesome!

**Comment by anuchandy** [comment]
@philcarbone, @cpunella this is addressed in the PR https://github.com/Azure/azure-libraries-for-net/pull/188 and will be available in the next release v1.7 scheduled for next week.

**Comment by hovsepm** [comment]
Fixed in master branch. Will be available in v1.7
