### ISSUE TITLE
PrefixDNS / FQDN not available for >10 minutes after server starts

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-libraries-for-net#353]
I have developed an Azure Function in C# (VS2017, ver 15.7.1) and used Microsoft.Azure.Management.Fluent v1.11.1 (2nd June 2018) to programatically create instances of a Linux server from an image in my GitHub/Azure Registry - see screenshot A.

Everything works as expected - the contain instance appears in Azure Portal and the FQDN appears in the overview page. However, I get repeated exceptions when I use a HttpClient from within my Azure Function to call the server API using this FQDN. The inner exception message is "The server name or address could not be resolved". After about 15 minutes the call to the server succeeds.

When I use the IP address rather than the FQDN as the HttpClient url, the call succeeds as expected - see screenshot B.

I conclude there is a lag of > 10 minutes between creating an Azure Container and its FQDN becoming available.  If correct, this significantly impacts the ultility of Azure Containers as there is no point in being able to create them in under 2 minutes if it takes a further 10 minutes for them to become available.

Please confirm whether or not this is a known issue with Azure Containers and give a timescale for a fix. I have raised a support request - 118060818345798

![_aaaazurecontainerfqdnproblem](https://user-images.githubusercontent.com/23079073/41141238-ddf1a158-6b0e-11e8-958d-9abacbd6c908.PNG)

**Comment by milismsft** [comment]
Adding @yangl900 to comment on the DNS propagation times.

@ImageQC Do you know how does this compare with other cloud resources that you can use to set a DNS label prefix, such as a Public IP? It is somehow expected for the DNS to take a while to be propagated through the internet before it is properly recognized by the authoritative name servers.

I don't see how the impact of this is so severe that makes Azure Container unusable; you mentioned that you already have the IP of it and that is a reasonable work around to use. When using container instances I will expect something more along the lines of bringing up a service very fast, run for a little while, then tear it down relatively soon after. Setting DNS's and stuff tells me you are expecting these services to run for much longer that what are initially intended for. It might be more efficient for you to set a Traffic Manager as the "facing" service then use it to register the container instances IPs to an established DNS instead of directly relying on the DNS of the container instance. 

And if I'm not mistaken the "_promise_" behind this cloud feature is to be able to get a resource **provisioned** for the user very fast but having your container instance service up and running and available to other apps it depends on all kinds of other factors such as: the container image size and whether it is cached or not, the time it takes for the image/app to start up, other settings that might be run as part of the container instance startup (i.e. DNS settings, volume mounting). Good design and implementation practices requires the user to take all these into account when building another app which relies on the container instance service rather than expecting a precise availability time.

**Comment by ImageQC** [comment]
The root problem would seem to be the time needed to propagate the DNS to the various servers on the internet as you suggested, so there isn't an easy fix for this. Therefore let's categorise it as 'known issue'.

I didn't say that this problem makes Azure Container unusable, but it does impact their utility. My application [(www.ovaryvis.org)](www.ovaryvis.org) needs an R server to perform classification, but it will only be used only occasionally, so I wanted to run it on demand rather than paying for a permanent server. Azure Containers seemed like a good solution as they spin-up in a few minutes and can then be shutdown after a pre-set period of inactivity. Unfortunately, I didn't see the issue of time delay for DNS propagation until testing. I've now redesigned the app to use the IP address, so it works fine; actually, Containers provides a great solution for me. However, I can imagine other applications that wouldn't work with a variable IP address and for those the DNS propagation delay issue might be a killer. 

There is also the issue of the uniqueness of the DNS prefix which suggests the need for some form of registry. Perhaps a solution would be to allow people to register a DNS prefix with their container registry and provide an name lookup facility such that the IP address was returned when the server was running and null when it wasn't. In this way people wouldn't have to wait for DNS propagation, but could still publish a standard name for the server. 

My other issue with Azure Containers is the wait needed for their creation using the API. This means my Azure Function runs for > 2minutes before returning - not a big problem, but sometimes I get repeat events from EventGrid which have to be handled. Would it be possible to return after kicking-off the spinning-up of the server and provide a facility (like EventGrid or container registry lookup) to provide the IP address (or DNS) when it was finally running? 

Thanks for you help. Hopefully these comments / feedback will help others.

**Comment by hovsepm** [comment]
Closing as fixed.
