### ISSUE TITLE
Listing WebApp DeploymentSlots suddenly stopped working

### ISSUE THREAD

**Issue by Jabe** [Azure/azure-libraries-for-net#435]
A few hours ago this code has stopped working:
```
var app = await AzureApi.WebApps.GetByIdAsync("...");

// this throws: Microsoft.Rest.ValidationException: ''resourceGroupName' cannot be null.'
await app.DeploymentSlots.ListAsync();
```

I can still get a specific deployment slot though:
```
await app.DeploymentSlots.GetByNameAsync("foobar");
```

The code was fine for months with version 1.11.1 (update to 1.14.0 didn't fix it) and now it suddenly stops working. Super weird. It seems as the Azure API has changed.

Any ideas?

**Comment by lauri-n** [comment]
I encountered the same problem yesterday and traced it to this API call:

`
GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/slots?api-version=2016-08-01 HTTP/1.1
`

It's called from `Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.ListSlotsWithHttpMessagesAsync` and since at least yesterday returns a null resourceGroup (extra content omitted for brevity):

```
{
	"value": [{
			"properties": {
				"resourceGroup": null
			}
	}]
}
```

This null value is then passed on to `Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.GetConfigurationSlotWithHttpMessagesAsync` where the argument validation catches the null value and throws an exception.

**Comment by Jabe** [comment]
I became frustrated and built a workaround. I've added a `DelegatingHandler` that intercepts the specific response and sets the `resourceGroup`. 😐

Have a look:  
[WorkaroundDelegatingHandler.cs](https://github.com/glueckkanja/azzipgo/blob/bd6c52ab8c6a2fa935ed52c0ab78d2abdd1bd765/AzZipGo/WorkaroundDelegatingHandler.cs)  
[Usage](https://github.com/glueckkanja/azzipgo/blob/bd6c52ab8c6a2fa935ed52c0ab78d2abdd1bd765/AzZipGo/BaseDeployAction.cs#L29)

**Comment by Jabe** [comment]
This was fixed a few days ago, my workaround is not needed anymore.

Please be more responsive in the future. 

![one-does-not-simply-break-a-productive-api](https://user-images.githubusercontent.com/10817/45691824-a173bb80-bb59-11e8-8140-ee5aafc54e8c.jpg)
