### ISSUE TITLE
Adding app settings to existing Function App creates a new storage account

### ISSUE THREAD

**Issue by david-jarman** [Azure/azure-libraries-for-net#457]
Creating a new storage account is an unintended consequence of calling

```CSharp
functionApp.Update()
.WithAppSetting("key", "value")
.Apply();
```
This also causes the currently deployed functions to be lost since the function app is now pointing at a new storage account.

The offending code is in [FunctionAppImpl.cs](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/FunctionAppImpl.cs) Line 163-166

I think the root cause of this issue is that the currentStorageAccount is never populated with the actual storage account that is associated with the function app

**Comment by david-jarman** [comment]
My hope was that the function app methods in the fluent SDK would be idempotent. As I've been looking through the code, it seems that this might not always be the case.

I thought I could work around this issue by adding the original connect storage account to the Update() using WithExistingStorageAccount, but that method ends up updating the WEBSITE_CONTENTSHARE app setting to a random resource name on Apply(), Now that I've debugged the issue, I've ended up with a bunch of different file shares in that storage account, and my functions that were deployed get wiped out.

I've been using fluent for a while, but functions are the first service I've used that offers methods that aren't idempotent.

**Comment by m-mertz** [comment]
Having the same issue. Just wanted to update an app setting and then the SDK tries to create a new storage account. Even fails in my case because the generated storage account name is too long (my function app name is 20 chars long).

In my case, the function app is on an app service plan. According to [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings), WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE are only required for consumption plan apps. But it looks like the SDK needs these settings to recognize that an app already has a storage account.

Strongly related to this, I don't think these settings should be defined at all when creating a new function app on an app service plan, but they are. Quick repro (inspect app settings of new app):

```csharp
IFunctionApp newFunctionApp = await azure.AppServices.FunctionApps
    .Define("functionAppName")
    .WithExistingAppServicePlan(appServicePlan)
    .WithExistingResourceGroup("resourceGroup")
    .WithExistingStorageAccount(storageAccount)
    .CreateAsync()
    .ConfigureAwait(false);
```

**Comment by m-mertz** [comment]
There's a simple workaround for app settings, and possibly other properties that are inherited from web apps. This works because a Function App is just a special Web App, so we can use those methods instead:

```csharp
IWebApp app = await azure.WebApps.GetByResourceGroupAsync(resourceGroup, functionAppName).ConfigureAwait(false);
await app.Update().WithAppSetting("testsetting", "value").ApplyAsync().ConfigureAwait(false);
```

Interestingly enough, the WebApp.List* methods don't show function apps, but they can be retrieved through the Get* methods.

**Comment by jonathanantoine** [comment]
Any update on this issue? Would love to see it closed :) Thanks @m-mertz for the workaround !

**Comment by benPearce1** [comment]
This is still an issue in 1.22. Seems to not just be App Settings
```
provisioningFunction = provisioningFunction.Update()
                    .WithExistingStorageAccount(storageAccount)
                    .WithRuntimeVersion(functionsRuntimeVersion).Apply();
```

**Comment by weidongxu-microsoft** [comment]
Fixed by https://github.com/Azure/azure-libraries-for-net/pull/761
