### ISSUE TITLE
Certificate Thumbprint mangled

### ISSUE THREAD

**Issue by ianlar** [Azure/azure-libraries-for-net#546]
I'm not sure how to add a certificate to an application and have the thumbprint show up correctly in the portal. Right now the thumbprint is the ASCII hex values of whatever the string passed to DefineCertificateCredential() is. Is this a bug, and if not, what's the right way to add a cert as an application key? This is what I'm currently doing, and the thumbprint in the portal shows up as 42424242:

```
            var app = azure.ActiveDirectoryApplications.GetByName(workerSP.Name);
            app.Update()
                .DefineCertificateCredential("BBBB")
                .WithAsymmetricX509Certificate()
                .WithPublicKey(workerCert.GetRawCertData())
                .Attach().Apply();
```

**Comment by praries880** [comment]
@jianghaolu This is most likely because of the following code (we read out the bytes in the name and then base 64 encode it) :
```c#
        internal CertificateCredentialImpl(string name, IHasCredential<T> parent)
            : base(name, new KeyCredential()
            {
                Usage = "Verify",
                CustomKeyIdentifier = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(name)),
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddYears(1)
            })
...
```
Code [here](https://github.com/Azure/azure-libraries-for-net/blob/5f85a978aaa0340e5ef9f9747d3fefe052ad2a2b/src/ResourceManagement/Graph.RBAC/CertificateCredentialImpl.cs#L147).

We do the same in [java fluent sdk](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/implementation/CertificateCredentialImpl.java#L53) as well.

**Comment by ChenTanyi** [comment]
@ianlar It doesn't matter when you use this certificate. It just has different display name.

If you really want to show the thumbprint in portal, you could use the `DefineCertificateCredential()` without parameter after .NET SDK 1.29.1. We have fixed it at https://github.com/Azure/azure-libraries-for-net/pull/930.
