### ISSUE TITLE
[BUG] Selecting function app by resource ID doesn’t seem supported

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-libraries-for-net#733]
**Describe the bug**
When trying to select a function app by resource ID it throws an exception even though resource Id is valid.

***Exception or Stack Trace***

> The specified ID "/subscriptions/411a9cd0-f057-4ae5-8def-cc1ea96a3933/resourceGroups/durable-entity-circuitbreaker/providers/Microsoft.Web/sites/jehollan-circuit-eh" is not a valid Azure resource ID.
--

***Code Snippet***
```csharp
await azure.AppServices.FunctionApps.GetById(resourceId).StopAsync();
```
**Expected behavior**
That’s a valid Resource ID.

**Additional Context**
I suspect resource IDs all up may be busted. I’m not sure why this check exists?
https://github.com/Azure/azure-libraries-for-net/blob/0ea10a867c2e759bb05a929726cd7b18c20b0a6b/src/ResourceManagement/ResourceManager/Core/ResourceId.cs#L40-L43

**Comment by weidongxu-microsoft** [comment]
It works fine for me.
`var funcApp = azure.AppServices.FunctionApps.GetById("/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/jianghaospring/providers/Microsoft.Web/sites/walkthrough-jianghaofunc");`

And I tried your exact resourceId `/subscriptions/411a9cd0-f057-4ae5-8def-cc1ea96a3933/resourceGroups/durable-entity-circuitbreaker/providers/Microsoft.Web/sites/jehollan-circuit-eh`
The response is (which is reasonable since I dont have that resource group)
```
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'durable-entity-circuitbreaker' could not be found."
  }
}
```

And that part of code should be OK. Basically resourceId is in the format of scope1/id1/scope2/id2... so the code expect that.

Maybe you can try a later SDK version? I am on 1.24.1

**Comment by weidongxu-microsoft** [comment]
Or maybe you have a extra space or invisible char before the first '/'.

**Comment by yaohaizh** [comment]
Close the issue as suggested. @jeffhollan feel free to reopen the issue if you have more questions.
